### ISSUE TITLE
Adds supports for secured vhosts (SSLEngine on)

### ISSUE THREAD

**Issue by egarbi** [robertdebock/ansible-role-httpd#5]
**Is your feature request related to a problem? Please describe.**
if I need a vhost like this:
```
LoadModule proxy_module /etc/httpd/modules/mod_proxy.so
LoadModule proxy_http_module /etc/httpd/modules/mod_proxy_http.so

<VirtualHost *:443>
   ServerName example.com
   SSLEngine on
   ProxyPreserveHost On
   ProxyPass / http://localhost:8080
   ProxyPassReverse / http://localhost:8080
</VirtualHost>
```

**Describe the solution you'd like**
I would like to include an extra template file to be able to add VirtualHost's listening on 
`{{ http_ssl_port}}` and with `SSLEngine on`.
Therefore I can proxy requests to a local non-secured port in a safe way.
 
Maybe there is already a way to do the same without having to add this feature, if so, could you please describe?

**Comment by robertdebock** [comment]
Hi,

This seems to be possible like this:

```yaml
      httpd_vhosts:
        - name: piratebay
          servername: piratebay.nl
          backend_url: "https://thepirate-bay.org/"
          proxy_preserve_host: Off
          proxy_requests: Off
```

This is documented in the README.md.
